FROM python:3.11
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV TZ="Europe/Moscow"
WORKDIR /code
COPY api /code/api
COPY db /code/db
COPY llm_scripts /code/llm_scripts
COPY messages /code/messages
COPY .env /code/
COPY app.py /code/
COPY front.py /code/
COPY cleaned_coffee.csv /code/
COPY pyproject_api.toml /code/pyproject.toml

RUN mkdir --parents /usr/local/share/ca-certificates/Yandex/ 
RUN wget "https://storage.yandexcloud.net/cloud-certs/RootCA.pem" --output-document /usr/local/share/ca-certificates/Yandex/RootCA.crt 
RUN wget "https://storage.yandexcloud.net/cloud-certs/IntermediateCA.pem"      --output-document /usr/local/share/ca-certificates/Yandex/IntermediateCA.crt 
RUN chmod 655 /usr/local/share/ca-certificates/Yandex/RootCA.crt      /usr/local/share/ca-certificates/Yandex/IntermediateCA.crt 
RUN update-ca-certificates
RUN python -m pip install --upgrade setuptools
RUN pip install poetry && poetry config virtualenvs.create false && poetry install --no-dev


EXPOSE 8097/tcp
CMD ["streamlit", "run", "front.py", "--server.address=0.0.0.0", "--server.port=8501"]